spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projet_fil_rouge?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: rootroot

  jpa:
    hibernate:
      ddl-auto: update
